title: David Salcedo # your name (or website title) here
logo: "/images/S-2.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Solid background in life sciences and expertise in omics data analysis (transcriptomics and proteomics)
  my primary objective is to devise and enhance methods that enable a comprehensive understanding of biological systems. 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">Google Scholar Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
