title: David Salcedo-Tacuma # your name (or website title) here
logo: "/images/S-2.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  With a solid background in life sciences and expertise in omics data analysis, specifically transcriptomics and proteomics research, 
  my primary objective is to devise and enhance methodologies that enable a comprehensive understanding of biological systems through big data analysis
  <br><br>
  Currently, my projects are centered on creating innovative tools to investigate novel molecules involved in degradation pathways. 
  This cutting-edge research not only expands our knowledge of these complex systems but also paves the way for future discoveries in the realm of molecular biology.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics:  # your Google Analytics tracking ID here
